/* eslint-disable */

const frames = [
  [{
    "x": 0,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 0,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 0,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 0,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 1,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 1,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 1,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 2,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 1,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 2,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 4,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 2,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 4,
    "color": "#FFF"
  }, {
    "x": 7,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 0,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 7,
    "color": "transparent"
  }],
  [{
    "x": 0,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 0,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 1,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 1,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 1,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 1,
    "color": "#ffb500"
  }, {
    "x": 0,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 2,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 2,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 2,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 1,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 2,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 4,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 2,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 4,
    "color": "#FFF"
  }, {
    "x": 7,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 0,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 7,
    "color": "transparent"
  }],
  [{
    "x": 0,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 1,
    "color": "#ffEE00"
  }, {
    "x": 1,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 2,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 2,
    "color": "#ffb500"
  }, {
    "x": 0,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 1,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 2,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 4,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 2,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 4,
    "color": "#FFF"
  }, {
    "x": 7,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 0,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 7,
    "color": "transparent"
  }],
  [{
    "x": 0,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 1,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 2,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 4,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 2,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 4,
    "color": "#FFF"
  }, {
    "x": 7,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 0,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 6,
    "color": "#ffEE00"
  }, {
    "x": 1,
    "y": 6,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 7,
    "color": "transparent"
  }],
  [{
    "x": 0,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 1,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 2,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 4,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 2,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 4,
    "color": "#FFF"
  }, {
    "x": 7,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 0,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 6,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 6,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 0,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 7,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 7,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 7,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 7,
    "color": "transparent"
  }],
  [{
    "x": 0,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 1,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 2,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 4,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 2,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 4,
    "color": "#FFF"
  }, {
    "x": 7,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 0,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 6,
    "color": "#ffEE00"
  }, {
    "x": 1,
    "y": 6,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 7,
    "color": "transparent"
  }],
  [{
    "x": 0,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 1,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 2,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 4,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 2,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 4,
    "color": "#FFF"
  }, {
    "x": 7,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 0,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 7,
    "color": "transparent"
  }],
  [{
    "x": 0,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 0,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 1,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 2,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 2,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 2,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 2,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 2,
    "color": "#ffb500"
  }, {
    "x": 0,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 1,
    "y": 3,
    "color": "#ff6633"
  }, {
    "x": 2,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 3,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 4,
    "y": 3,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 6,
    "y": 3,
    "color": "#ffb500"
  }, {
    "x": 7,
    "y": 3,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 4,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 2,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 4,
    "color": "#ffb500"
  }, {
    "x": 5,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 4,
    "color": "#FFF"
  }, {
    "x": 7,
    "y": 4,
    "color": "#ffEE00"
  }, {
    "x": 0,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 5,
    "color": "#ffb500"
  }, {
    "x": 4,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 5,
    "y": 5,
    "color": "#ffEE00"
  }, {
    "x": 6,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 5,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 6,
    "color": "#ffb500"
  }, {
    "x": 3,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 6,
    "color": "transparent"
  }, {
    "x": 0,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 1,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 2,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 3,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 4,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 5,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 6,
    "y": 7,
    "color": "transparent"
  }, {
    "x": 7,
    "y": 7,
    "color": "transparent"
  }]
];

export default frames;
