/* eslint-disable */

const frames = [
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":1,
        "color":"transparent"
     },
     {
        "x":1,
        "y":1,
        "color":"transparent"
     },
     {
        "x":2,
        "y":1,
        "color":"transparent"
     },
     {
        "x":3,
        "y":1,
        "color":"transparent"
     },
     {
        "x":4,
        "y":1,
        "color":"transparent"
     },
     {
        "x":5,
        "y":1,
        "color":"transparent"
     },
     {
        "x":6,
        "y":1,
        "color":"transparent"
     },
     {
        "x":7,
        "y":1,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"transparent"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"transparent"
     },
     {
        "x":3,
        "y":2,
        "color":"transparent"
     },
     {
        "x":4,
        "y":2,
        "color":"transparent"
     },
     {
        "x":5,
        "y":2,
        "color":"transparent"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"transparent"
     },
     {
        "x":0,
        "y":3,
        "color":"transparent"
     },
     {
        "x":1,
        "y":3,
        "color":"transparent"
     },
     {
        "x":2,
        "y":3,
        "color":"transparent"
     },
     {
        "x":3,
        "y":3,
        "color":"#00ccff"
     },
     {
        "x":4,
        "y":3,
        "color":"#00ccff"
     },
     {
        "x":5,
        "y":3,
        "color":"transparent"
     },
     {
        "x":6,
        "y":3,
        "color":"transparent"
     },
     {
        "x":7,
        "y":3,
        "color":"transparent"
     },
     {
        "x":0,
        "y":4,
        "color":"transparent"
     },
     {
        "x":1,
        "y":4,
        "color":"transparent"
     },
     {
        "x":2,
        "y":4,
        "color":"transparent"
     },
     {
        "x":3,
        "y":4,
        "color":"#00ccff"
     },
     {
        "x":4,
        "y":4,
        "color":"#00ccff"
     },
     {
        "x":5,
        "y":4,
        "color":"transparent"
     },
     {
        "x":6,
        "y":4,
        "color":"transparent"
     },
     {
        "x":7,
        "y":4,
        "color":"transparent"
     },
     {
        "x":0,
        "y":5,
        "color":"transparent"
     },
     {
        "x":1,
        "y":5,
        "color":"transparent"
     },
     {
        "x":2,
        "y":5,
        "color":"transparent"
     },
     {
        "x":3,
        "y":5,
        "color":"transparent"
     },
     {
        "x":4,
        "y":5,
        "color":"transparent"
     },
     {
        "x":5,
        "y":5,
        "color":"transparent"
     },
     {
        "x":6,
        "y":5,
        "color":"transparent"
     },
     {
        "x":7,
        "y":5,
        "color":"transparent"
     },
     {
        "x":0,
        "y":6,
        "color":"transparent"
     },
     {
        "x":1,
        "y":6,
        "color":"transparent"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"transparent"
     },
     {
        "x":4,
        "y":6,
        "color":"transparent"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"transparent"
     },
     {
        "x":7,
        "y":6,
        "color":"transparent"
     },
     {
        "x":0,
        "y":7,
        "color":"transparent"
     },
     {
        "x":1,
        "y":7,
        "color":"transparent"
     },
     {
        "x":2,
        "y":7,
        "color":"transparent"
     },
     {
        "x":3,
        "y":7,
        "color":"transparent"
     },
     {
        "x":4,
        "y":7,
        "color":"transparent"
     },
     {
        "x":5,
        "y":7,
        "color":"transparent"
     },
     {
        "x":6,
        "y":7,
        "color":"transparent"
     },
     {
        "x":7,
        "y":7,
        "color":"transparent"
     }
  ],
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":1,
        "color":"transparent"
     },
     {
        "x":1,
        "y":1,
        "color":"transparent"
     },
     {
        "x":2,
        "y":1,
        "color":"transparent"
     },
     {
        "x":3,
        "y":1,
        "color":"transparent"
     },
     {
        "x":4,
        "y":1,
        "color":"transparent"
     },
     {
        "x":5,
        "y":1,
        "color":"transparent"
     },
     {
        "x":6,
        "y":1,
        "color":"transparent"
     },
     {
        "x":7,
        "y":1,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"transparent"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"transparent"
     },
     {
        "x":3,
        "y":2,
        "color":"#0066ff"
     },
     {
        "x":4,
        "y":2,
        "color":"#0066ff"
     },
     {
        "x":5,
        "y":2,
        "color":"transparent"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"transparent"
     },
     {
        "x":0,
        "y":3,
        "color":"transparent"
     },
     {
        "x":1,
        "y":3,
        "color":"transparent"
     },
     {
        "x":2,
        "y":3,
        "color":"#0066ff"
     },
     {
        "x":3,
        "y":3,
        "color":"transparent"
     },
     {
        "x":4,
        "y":3,
        "color":"transparent"
     },
     {
        "x":5,
        "y":3,
        "color":"#0066ff"
     },
     {
        "x":6,
        "y":3,
        "color":"transparent"
     },
     {
        "x":7,
        "y":3,
        "color":"transparent"
     },
     {
        "x":0,
        "y":4,
        "color":"transparent"
     },
     {
        "x":1,
        "y":4,
        "color":"transparent"
     },
     {
        "x":2,
        "y":4,
        "color":"#0066ff"
     },
     {
        "x":3,
        "y":4,
        "color":"transparent"
     },
     {
        "x":4,
        "y":4,
        "color":"transparent"
     },
     {
        "x":5,
        "y":4,
        "color":"#0066ff"
     },
     {
        "x":6,
        "y":4,
        "color":"transparent"
     },
     {
        "x":7,
        "y":4,
        "color":"transparent"
     },
     {
        "x":0,
        "y":5,
        "color":"transparent"
     },
     {
        "x":1,
        "y":5,
        "color":"transparent"
     },
     {
        "x":2,
        "y":5,
        "color":"transparent"
     },
     {
        "x":3,
        "y":5,
        "color":"#0066ff"
     },
     {
        "x":4,
        "y":5,
        "color":"#0066ff"
     },
     {
        "x":5,
        "y":5,
        "color":"transparent"
     },
     {
        "x":6,
        "y":5,
        "color":"transparent"
     },
     {
        "x":7,
        "y":5,
        "color":"transparent"
     },
     {
        "x":0,
        "y":6,
        "color":"transparent"
     },
     {
        "x":1,
        "y":6,
        "color":"transparent"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"transparent"
     },
     {
        "x":4,
        "y":6,
        "color":"transparent"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"transparent"
     },
     {
        "x":7,
        "y":6,
        "color":"transparent"
     },
     {
        "x":0,
        "y":7,
        "color":"transparent"
     },
     {
        "x":1,
        "y":7,
        "color":"transparent"
     },
     {
        "x":2,
        "y":7,
        "color":"transparent"
     },
     {
        "x":3,
        "y":7,
        "color":"transparent"
     },
     {
        "x":4,
        "y":7,
        "color":"transparent"
     },
     {
        "x":5,
        "y":7,
        "color":"transparent"
     },
     {
        "x":6,
        "y":7,
        "color":"transparent"
     },
     {
        "x":7,
        "y":7,
        "color":"transparent"
     }
  ],
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":1,
        "color":"transparent"
     },
     {
        "x":1,
        "y":1,
        "color":"transparent"
     },
     {
        "x":2,
        "y":1,
        "color":"transparent"
     },
     {
        "x":3,
        "y":1,
        "color":"#0011EE"
     },
     {
        "x":4,
        "y":1,
        "color":"#0011EE"
     },
     {
        "x":5,
        "y":1,
        "color":"transparent"
     },
     {
        "x":6,
        "y":1,
        "color":"transparent"
     },
     {
        "x":7,
        "y":1,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"transparent"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"#0011EE"
     },
     {
        "x":3,
        "y":2,
        "color":"transparent"
     },
     {
        "x":4,
        "y":2,
        "color":"transparent"
     },
     {
        "x":5,
        "y":2,
        "color":"#0011EE"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"transparent"
     },
     {
        "x":0,
        "y":3,
        "color":"transparent"
     },
     {
        "x":1,
        "y":3,
        "color":"#0011EE"
     },
     {
        "x":2,
        "y":3,
        "color":"transparent"
     },
     {
        "x":3,
        "y":3,
        "color":"transparent"
     },
     {
        "x":4,
        "y":3,
        "color":"transparent"
     },
     {
        "x":5,
        "y":3,
        "color":"transparent"
     },
     {
        "x":6,
        "y":3,
        "color":"#0011EE"
     },
     {
        "x":7,
        "y":3,
        "color":"transparent"
     },
     {
        "x":0,
        "y":4,
        "color":"transparent"
     },
     {
        "x":1,
        "y":4,
        "color":"#0011EE"
     },
     {
        "x":2,
        "y":4,
        "color":"transparent"
     },
     {
        "x":3,
        "y":4,
        "color":"transparent"
     },
     {
        "x":4,
        "y":4,
        "color":"transparent"
     },
     {
        "x":5,
        "y":4,
        "color":"transparent"
     },
     {
        "x":6,
        "y":4,
        "color":"#0011EE"
     },
     {
        "x":7,
        "y":4,
        "color":"transparent"
     },
     {
        "x":0,
        "y":5,
        "color":"transparent"
     },
     {
        "x":1,
        "y":5,
        "color":"transparent"
     },
     {
        "x":2,
        "y":5,
        "color":"#0011EE"
     },
     {
        "x":3,
        "y":5,
        "color":"transparent"
     },
     {
        "x":4,
        "y":5,
        "color":"transparent"
     },
     {
        "x":5,
        "y":5,
        "color":"#0011EE"
     },
     {
        "x":6,
        "y":5,
        "color":"transparent"
     },
     {
        "x":7,
        "y":5,
        "color":"transparent"
     },
     {
        "x":0,
        "y":6,
        "color":"transparent"
     },
     {
        "x":1,
        "y":6,
        "color":"transparent"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"#0011EE"
     },
     {
        "x":4,
        "y":6,
        "color":"#0011EE"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"transparent"
     },
     {
        "x":7,
        "y":6,
        "color":"transparent"
     },
     {
        "x":0,
        "y":7,
        "color":"transparent"
     },
     {
        "x":1,
        "y":7,
        "color":"transparent"
     },
     {
        "x":2,
        "y":7,
        "color":"transparent"
     },
     {
        "x":3,
        "y":7,
        "color":"transparent"
     },
     {
        "x":4,
        "y":7,
        "color":"transparent"
     },
     {
        "x":5,
        "y":7,
        "color":"transparent"
     },
     {
        "x":6,
        "y":7,
        "color":"transparent"
     },
     {
        "x":7,
        "y":7,
        "color":"transparent"
     }
  ],
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"#4400ff"
     },
     {
        "x":3,
        "y":0,
        "color":"#4400ff"
     },
     {
        "x":4,
        "y":0,
        "color":"#4400ff"
     },
     {
        "x":5,
        "y":0,
        "color":"#4400ff"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":1,
        "color":"transparent"
     },
     {
        "x":1,
        "y":1,
        "color":"#4400ff"
     },
     {
        "x":2,
        "y":1,
        "color":"transparent"
     },
     {
        "x":3,
        "y":1,
        "color":"transparent"
     },
     {
        "x":4,
        "y":1,
        "color":"transparent"
     },
     {
        "x":5,
        "y":1,
        "color":"transparent"
     },
     {
        "x":6,
        "y":1,
        "color":"#4400ff"
     },
     {
        "x":7,
        "y":1,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"#4400ff"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"transparent"
     },
     {
        "x":3,
        "y":2,
        "color":"transparent"
     },
     {
        "x":4,
        "y":2,
        "color":"transparent"
     },
     {
        "x":5,
        "y":2,
        "color":"transparent"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"#4400ff"
     },
     {
        "x":0,
        "y":3,
        "color":"#4400ff"
     },
     {
        "x":1,
        "y":3,
        "color":"transparent"
     },
     {
        "x":2,
        "y":3,
        "color":"transparent"
     },
     {
        "x":3,
        "y":3,
        "color":"transparent"
     },
     {
        "x":4,
        "y":3,
        "color":"transparent"
     },
     {
        "x":5,
        "y":3,
        "color":"transparent"
     },
     {
        "x":6,
        "y":3,
        "color":"transparent"
     },
     {
        "x":7,
        "y":3,
        "color":"#4400ff"
     },
     {
        "x":0,
        "y":4,
        "color":"#4400ff"
     },
     {
        "x":1,
        "y":4,
        "color":"transparent"
     },
     {
        "x":2,
        "y":4,
        "color":"transparent"
     },
     {
        "x":3,
        "y":4,
        "color":"transparent"
     },
     {
        "x":4,
        "y":4,
        "color":"transparent"
     },
     {
        "x":5,
        "y":4,
        "color":"transparent"
     },
     {
        "x":6,
        "y":4,
        "color":"transparent"
     },
     {
        "x":7,
        "y":4,
        "color":"#4400ff"
     },
     {
        "x":0,
        "y":5,
        "color":"#4400ff"
     },
     {
        "x":1,
        "y":5,
        "color":"transparent"
     },
     {
        "x":2,
        "y":5,
        "color":"transparent"
     },
     {
        "x":3,
        "y":5,
        "color":"transparent"
     },
     {
        "x":4,
        "y":5,
        "color":"transparent"
     },
     {
        "x":5,
        "y":5,
        "color":"transparent"
     },
     {
        "x":6,
        "y":5,
        "color":"transparent"
     },
     {
        "x":7,
        "y":5,
        "color":"#4400ff"
     },
     {
        "x":0,
        "y":6,
        "color":"transparent"
     },
     {
        "x":1,
        "y":6,
        "color":"#4400ff"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"transparent"
     },
     {
        "x":4,
        "y":6,
        "color":"transparent"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"#4400ff"
     },
     {
        "x":7,
        "y":6,
        "color":"transparent"
     },
     {
        "x":0,
        "y":7,
        "color":"transparent"
     },
     {
        "x":1,
        "y":7,
        "color":"transparent"
     },
     {
        "x":2,
        "y":7,
        "color":"#4400ff"
     },
     {
        "x":3,
        "y":7,
        "color":"#4400ff"
     },
     {
        "x":4,
        "y":7,
        "color":"#4400ff"
     },
     {
        "x":5,
        "y":7,
        "color":"#4400ff"
     },
     {
        "x":6,
        "y":7,
        "color":"transparent"
     },
     {
        "x":7,
        "y":7,
        "color":"transparent"
     }
  ],
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"#9900ff"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"#9900ff"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":1,
        "color":"#9900ff"
     },
     {
        "x":1,
        "y":1,
        "color":"transparent"
     },
     {
        "x":2,
        "y":1,
        "color":"transparent"
     },
     {
        "x":3,
        "y":1,
        "color":"transparent"
     },
     {
        "x":4,
        "y":1,
        "color":"transparent"
     },
     {
        "x":5,
        "y":1,
        "color":"transparent"
     },
     {
        "x":6,
        "y":1,
        "color":"transparent"
     },
     {
        "x":7,
        "y":1,
        "color":"#9900ff"
     },
     {
        "x":0,
        "y":2,
        "color":"transparent"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"transparent"
     },
     {
        "x":3,
        "y":2,
        "color":"transparent"
     },
     {
        "x":4,
        "y":2,
        "color":"transparent"
     },
     {
        "x":5,
        "y":2,
        "color":"transparent"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"transparent"
     },
     {
        "x":0,
        "y":3,
        "color":"transparent"
     },
     {
        "x":1,
        "y":3,
        "color":"transparent"
     },
     {
        "x":2,
        "y":3,
        "color":"transparent"
     },
     {
        "x":3,
        "y":3,
        "color":"#333"
     },
     {
        "x":4,
        "y":3,
        "color":"#333"
     },
     {
        "x":5,
        "y":3,
        "color":"transparent"
     },
     {
        "x":6,
        "y":3,
        "color":"transparent"
     },
     {
        "x":7,
        "y":3,
        "color":"transparent"
     },
     {
        "x":0,
        "y":4,
        "color":"transparent"
     },
     {
        "x":1,
        "y":4,
        "color":"transparent"
     },
     {
        "x":2,
        "y":4,
        "color":"transparent"
     },
     {
        "x":3,
        "y":4,
        "color":"#333"
     },
     {
        "x":4,
        "y":4,
        "color":"#333"
     },
     {
        "x":5,
        "y":4,
        "color":"transparent"
     },
     {
        "x":6,
        "y":4,
        "color":"transparent"
     },
     {
        "x":7,
        "y":4,
        "color":"transparent"
     },
     {
        "x":0,
        "y":5,
        "color":"transparent"
     },
     {
        "x":1,
        "y":5,
        "color":"transparent"
     },
     {
        "x":2,
        "y":5,
        "color":"transparent"
     },
     {
        "x":3,
        "y":5,
        "color":"transparent"
     },
     {
        "x":4,
        "y":5,
        "color":"transparent"
     },
     {
        "x":5,
        "y":5,
        "color":"transparent"
     },
     {
        "x":6,
        "y":5,
        "color":"transparent"
     },
     {
        "x":7,
        "y":5,
        "color":"transparent"
     },
     {
        "x":0,
        "y":6,
        "color":"#9900ff"
     },
     {
        "x":1,
        "y":6,
        "color":"transparent"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"transparent"
     },
     {
        "x":4,
        "y":6,
        "color":"transparent"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"transparent"
     },
     {
        "x":7,
        "y":6,
        "color":"#9900ff"
     },
     {
        "x":0,
        "y":7,
        "color":"transparent"
     },
     {
        "x":1,
        "y":7,
        "color":"#9900ff"
     },
     {
        "x":2,
        "y":7,
        "color":"transparent"
     },
     {
        "x":3,
        "y":7,
        "color":"transparent"
     },
     {
        "x":4,
        "y":7,
        "color":"transparent"
     },
     {
        "x":5,
        "y":7,
        "color":"transparent"
     },
     {
        "x":6,
        "y":7,
        "color":"#9900ff"
     },
     {
        "x":7,
        "y":7,
        "color":"transparent"
     }
  ],
  [
     {
        "x":0,
        "y":0,
        "color":"#fd7fff"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"#fd7fff"
     },
     {
        "x":0,
        "y":1,
        "color":"transparent"
     },
     {
        "x":1,
        "y":1,
        "color":"transparent"
     },
     {
        "x":2,
        "y":1,
        "color":"transparent"
     },
     {
        "x":3,
        "y":1,
        "color":"transparent"
     },
     {
        "x":4,
        "y":1,
        "color":"transparent"
     },
     {
        "x":5,
        "y":1,
        "color":"transparent"
     },
     {
        "x":6,
        "y":1,
        "color":"transparent"
     },
     {
        "x":7,
        "y":1,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"transparent"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"transparent"
     },
     {
        "x":3,
        "y":2,
        "color":"transparent"
     },
     {
        "x":4,
        "y":2,
        "color":"transparent"
     },
     {
        "x":5,
        "y":2,
        "color":"transparent"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"transparent"
     },
     {
        "x":0,
        "y":3,
        "color":"transparent"
     },
     {
        "x":1,
        "y":3,
        "color":"transparent"
     },
     {
        "x":2,
        "y":3,
        "color":"transparent"
     },
     {
        "x":3,
        "y":3,
        "color":"#777"
     },
     {
        "x":4,
        "y":3,
        "color":"#777"
     },
     {
        "x":5,
        "y":3,
        "color":"transparent"
     },
     {
        "x":6,
        "y":3,
        "color":"transparent"
     },
     {
        "x":7,
        "y":3,
        "color":"transparent"
     },
     {
        "x":0,
        "y":4,
        "color":"transparent"
     },
     {
        "x":1,
        "y":4,
        "color":"transparent"
     },
     {
        "x":2,
        "y":4,
        "color":"transparent"
     },
     {
        "x":3,
        "y":4,
        "color":"#777"
     },
     {
        "x":4,
        "y":4,
        "color":"#777"
     },
     {
        "x":5,
        "y":4,
        "color":"transparent"
     },
     {
        "x":6,
        "y":4,
        "color":"transparent"
     },
     {
        "x":7,
        "y":4,
        "color":"transparent"
     },
     {
        "x":0,
        "y":5,
        "color":"transparent"
     },
     {
        "x":1,
        "y":5,
        "color":"transparent"
     },
     {
        "x":2,
        "y":5,
        "color":"transparent"
     },
     {
        "x":3,
        "y":5,
        "color":"transparent"
     },
     {
        "x":4,
        "y":5,
        "color":"transparent"
     },
     {
        "x":5,
        "y":5,
        "color":"transparent"
     },
     {
        "x":6,
        "y":5,
        "color":"transparent"
     },
     {
        "x":7,
        "y":5,
        "color":"transparent"
     },
     {
        "x":0,
        "y":6,
        "color":"transparent"
     },
     {
        "x":1,
        "y":6,
        "color":"transparent"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"transparent"
     },
     {
        "x":4,
        "y":6,
        "color":"transparent"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"transparent"
     },
     {
        "x":7,
        "y":6,
        "color":"transparent"
     },
     {
        "x":0,
        "y":7,
        "color":"#fd7fff"
     },
     {
        "x":1,
        "y":7,
        "color":"transparent"
     },
     {
        "x":2,
        "y":7,
        "color":"transparent"
     },
     {
        "x":3,
        "y":7,
        "color":"transparent"
     },
     {
        "x":4,
        "y":7,
        "color":"transparent"
     },
     {
        "x":5,
        "y":7,
        "color":"transparent"
     },
     {
        "x":6,
        "y":7,
        "color":"transparent"
     },
     {
        "x":7,
        "y":7,
        "color":"#fd7fff"
     }
  ],
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":1,
        "color":"transparent"
     },
     {
        "x":1,
        "y":1,
        "color":"transparent"
     },
     {
        "x":2,
        "y":1,
        "color":"transparent"
     },
     {
        "x":3,
        "y":1,
        "color":"transparent"
     },
     {
        "x":4,
        "y":1,
        "color":"transparent"
     },
     {
        "x":5,
        "y":1,
        "color":"transparent"
     },
     {
        "x":6,
        "y":1,
        "color":"transparent"
     },
     {
        "x":7,
        "y":1,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"transparent"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"transparent"
     },
     {
        "x":3,
        "y":2,
        "color":"transparent"
     },
     {
        "x":4,
        "y":2,
        "color":"transparent"
     },
     {
        "x":5,
        "y":2,
        "color":"transparent"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"transparent"
     },
     {
        "x":0,
        "y":3,
        "color":"transparent"
     },
     {
        "x":1,
        "y":3,
        "color":"transparent"
     },
     {
        "x":2,
        "y":3,
        "color":"transparent"
     },
     {
        "x":3,
        "y":3,
        "color":"#aaa"
     },
     {
        "x":4,
        "y":3,
        "color":"#aaa"
     },
     {
        "x":5,
        "y":3,
        "color":"transparent"
     },
     {
        "x":6,
        "y":3,
        "color":"transparent"
     },
     {
        "x":7,
        "y":3,
        "color":"transparent"
     },
     {
        "x":0,
        "y":4,
        "color":"transparent"
     },
     {
        "x":1,
        "y":4,
        "color":"transparent"
     },
     {
        "x":2,
        "y":4,
        "color":"transparent"
     },
     {
        "x":3,
        "y":4,
        "color":"#aaa"
     },
     {
        "x":4,
        "y":4,
        "color":"#aaa"
     },
     {
        "x":5,
        "y":4,
        "color":"transparent"
     },
     {
        "x":6,
        "y":4,
        "color":"transparent"
     },
     {
        "x":7,
        "y":4,
        "color":"transparent"
     },
     {
        "x":0,
        "y":5,
        "color":"transparent"
     },
     {
        "x":1,
        "y":5,
        "color":"transparent"
     },
     {
        "x":2,
        "y":5,
        "color":"transparent"
     },
     {
        "x":3,
        "y":5,
        "color":"transparent"
     },
     {
        "x":4,
        "y":5,
        "color":"transparent"
     },
     {
        "x":5,
        "y":5,
        "color":"transparent"
     },
     {
        "x":6,
        "y":5,
        "color":"transparent"
     },
     {
        "x":7,
        "y":5,
        "color":"transparent"
     },
     {
        "x":0,
        "y":6,
        "color":"transparent"
     },
     {
        "x":1,
        "y":6,
        "color":"transparent"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"transparent"
     },
     {
        "x":4,
        "y":6,
        "color":"transparent"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"transparent"
     },
     {
        "x":7,
        "y":6,
        "color":"transparent"
     },
     {
        "x":0,
        "y":7,
        "color":"transparent"
     },
     {
        "x":1,
        "y":7,
        "color":"transparent"
     },
     {
        "x":2,
        "y":7,
        "color":"transparent"
     },
     {
        "x":3,
        "y":7,
        "color":"transparent"
     },
     {
        "x":4,
        "y":7,
        "color":"transparent"
     },
     {
        "x":5,
        "y":7,
        "color":"transparent"
     },
     {
        "x":6,
        "y":7,
        "color":"transparent"
     },
     {
        "x":7,
        "y":7,
        "color":"transparent"
     }
  ]
]

export default frames;