/* eslint-disable */

const frames = [
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":8,
        "y":0,
        "color":"transparent"
     },
     {
        "x":9,
        "y":0,
        "color":"transparent"
     },
     {
        "x":10,
        "y":0,
        "color":"transparent"
     },
     {
        "x":11,
        "y":0,
        "color":"transparent"
     },
     {
        "x":12,
        "y":0,
        "color":"transparent"
     },
     {
        "x":13,
        "y":0,
        "color":"transparent"
     },
     {
        "x":14,
        "y":0,
        "color":"transparent"
     },
     {
        "x":15,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"transparent"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"#99ff00"
     },
     {
        "x":3,
        "y":2,
        "color":"transparent"
     },
     {
        "x":4,
        "y":2,
        "color":"transparent"
     },
     {
        "x":5,
        "y":2,
        "color":"#99ff00"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"transparent"
     },
     {
        "x":8,
        "y":2,
        "color":"#99ff00"
     },
     {
        "x":9,
        "y":2,
        "color":"transparent"
     },
     {
        "x":10,
        "y":2,
        "color":"transparent"
     },
     {
        "x":11,
        "y":2,
        "color":"#ffEE00"
     },
     {
        "x":12,
        "y":2,
        "color":"transparent"
     },
     {
        "x":13,
        "y":2,
        "color":"transparent"
     },
     {
        "x":14,
        "y":2,
        "color":"#ffb500"
     },
     {
        "x":15,
        "y":2,
        "color":"transparent"
     },
     {
        "x":0,
        "y":4,
        "color":"#99ff00"
     },
     {
        "x":1,
        "y":4,
        "color":"transparent"
     },
     {
        "x":2,
        "y":4,
        "color":"transparent"
     },
     {
        "x":3,
        "y":4,
        "color":"#99ff00"
     },
     {
        "x":4,
        "y":4,
        "color":"transparent"
     },
     {
        "x":5,
        "y":4,
        "color":"transparent"
     },
     {
        "x":6,
        "y":4,
        "color":"#99ff00"
     },
     {
        "x":7,
        "y":4,
        "color":"transparent"
     },
     {
        "x":8,
        "y":4,
        "color":"transparent"
     },
     {
        "x":9,
        "y":4,
        "color":"#99ff00"
     },
     {
        "x":10,
        "y":4,
        "color":"transparent"
     },
     {
        "x":11,
        "y":4,
        "color":"transparent"
     },
     {
        "x":12,
        "y":4,
        "color":"#ffEE00"
     },
     {
        "x":13,
        "y":4,
        "color":"transparent"
     },
     {
        "x":14,
        "y":4,
        "color":"transparent"
     },
     {
        "x":15,
        "y":4,
        "color":"#ffb500"
     },
     {
        "x":0,
        "y":6,
        "color":"transparent"
     },
     {
        "x":1,
        "y":6,
        "color":"#99ff00"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"transparent"
     },
     {
        "x":4,
        "y":6,
        "color":"#99ff00"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"transparent"
     },
     {
        "x":7,
        "y":6,
        "color":"#99ff00"
     },
     {
        "x":8,
        "y":6,
        "color":"transparent"
     },
     {
        "x":9,
        "y":6,
        "color":"transparent"
     },
     {
        "x":10,
        "y":6,
        "color":"#99ff00"
     },
     {
        "x":11,
        "y":6,
        "color":"transparent"
     },
     {
        "x":12,
        "y":6,
        "color":"transparent"
     },
     {
        "x":13,
        "y":6,
        "color":"#ffEE00"
     },
     {
        "x":14,
        "y":6,
        "color":"transparent"
     },
     {
        "x":15,
        "y":6,
        "color":"transparent"
     },
     {
        "x":0,
        "y":8,
        "color":"transparent"
     },
     {
        "x":1,
        "y":8,
        "color":"transparent"
     },
     {
        "x":2,
        "y":8,
        "color":"#99ff00"
     },
     {
        "x":3,
        "y":8,
        "color":"transparent"
     },
     {
        "x":4,
        "y":8,
        "color":"transparent"
     },
     {
        "x":5,
        "y":8,
        "color":"#99ff00"
     },
     {
        "x":6,
        "y":8,
        "color":"transparent"
     },
     {
        "x":7,
        "y":8,
        "color":"transparent"
     },
     {
        "x":8,
        "y":8,
        "color":"#99ff00"
     },
     {
        "x":9,
        "y":8,
        "color":"transparent"
     },
     {
        "x":10,
        "y":8,
        "color":"transparent"
     },
     {
        "x":11,
        "y":8,
        "color":"#99ff00"
     },
     {
        "x":12,
        "y":8,
        "color":"transparent"
     },
     {
        "x":13,
        "y":8,
        "color":"transparent"
     },
     {
        "x":14,
        "y":8,
        "color":"#ffEE00"
     },
     {
        "x":15,
        "y":8,
        "color":"transparent"
     },
     {
        "x":0,
        "y":10,
        "color":"#00ccff"
     },
     {
        "x":1,
        "y":10,
        "color":"transparent"
     },
     {
        "x":2,
        "y":10,
        "color":"transparent"
     },
     {
        "x":3,
        "y":10,
        "color":"#99ff00"
     },
     {
        "x":4,
        "y":10,
        "color":"transparent"
     },
     {
        "x":5,
        "y":10,
        "color":"transparent"
     },
     {
        "x":6,
        "y":10,
        "color":"#99ff00"
     },
     {
        "x":7,
        "y":10,
        "color":"transparent"
     },
     {
        "x":8,
        "y":10,
        "color":"transparent"
     },
     {
        "x":9,
        "y":10,
        "color":"#99ff00"
     },
     {
        "x":10,
        "y":10,
        "color":"transparent"
     },
     {
        "x":11,
        "y":10,
        "color":"transparent"
     },
     {
        "x":12,
        "y":10,
        "color":"#99ff00"
     },
     {
        "x":13,
        "y":10,
        "color":"transparent"
     },
     {
        "x":14,
        "y":10,
        "color":"transparent"
     },
     {
        "x":15,
        "y":10,
        "color":"#ffEE00"
     },
     {
        "x":0,
        "y":12,
        "color":"transparent"
     },
     {
        "x":1,
        "y":12,
        "color":"#00ccff"
     },
     {
        "x":2,
        "y":12,
        "color":"transparent"
     },
     {
        "x":3,
        "y":12,
        "color":"transparent"
     },
     {
        "x":4,
        "y":12,
        "color":"#99ff00"
     },
     {
        "x":5,
        "y":12,
        "color":"transparent"
     },
     {
        "x":6,
        "y":12,
        "color":"transparent"
     },
     {
        "x":7,
        "y":12,
        "color":"#99ff00"
     },
     {
        "x":8,
        "y":12,
        "color":"transparent"
     },
     {
        "x":9,
        "y":12,
        "color":"transparent"
     },
     {
        "x":10,
        "y":12,
        "color":"#99ff00"
     },
     {
        "x":11,
        "y":12,
        "color":"transparent"
     },
     {
        "x":12,
        "y":12,
        "color":"transparent"
     },
     {
        "x":13,
        "y":12,
        "color":"#99ff00"
     },
     {
        "x":14,
        "y":12,
        "color":"transparent"
     },
     {
        "x":15,
        "y":12,
        "color":"transparent"
     },
     {
        "x":0,
        "y":14,
        "color":"transparent"
     },
     {
        "x":1,
        "y":14,
        "color":"transparent"
     },
     {
        "x":2,
        "y":14,
        "color":"transparent"
     },
     {
        "x":3,
        "y":14,
        "color":"transparent"
     },
     {
        "x":4,
        "y":14,
        "color":"transparent"
     },
     {
        "x":5,
        "y":14,
        "color":"transparent"
     },
     {
        "x":6,
        "y":14,
        "color":"transparent"
     },
     {
        "x":7,
        "y":14,
        "color":"transparent"
     },
     {
        "x":8,
        "y":14,
        "color":"transparent"
     },
     {
        "x":9,
        "y":14,
        "color":"transparent"
     },
     {
        "x":10,
        "y":14,
        "color":"transparent"
     },
     {
        "x":11,
        "y":14,
        "color":"transparent"
     },
     {
        "x":12,
        "y":14,
        "color":"transparent"
     },
     {
        "x":13,
        "y":14,
        "color":"transparent"
     },
     {
        "x":14,
        "y":14,
        "color":"transparent"
     },
     {
        "x":15,
        "y":14,
        "color":"transparent"
     }
  ],
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":8,
        "y":0,
        "color":"transparent"
     },
     {
        "x":9,
        "y":0,
        "color":"transparent"
     },
     {
        "x":10,
        "y":0,
        "color":"transparent"
     },
     {
        "x":11,
        "y":0,
        "color":"transparent"
     },
     {
        "x":12,
        "y":0,
        "color":"transparent"
     },
     {
        "x":13,
        "y":0,
        "color":"transparent"
     },
     {
        "x":14,
        "y":0,
        "color":"transparent"
     },
     {
        "x":15,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"transparent"
     },
     {
        "x":1,
        "y":2,
        "color":"#31dd00"
     },
     {
        "x":2,
        "y":2,
        "color":"transparent"
     },
     {
        "x":3,
        "y":2,
        "color":"transparent"
     },
     {
        "x":4,
        "y":2,
        "color":"#31dd00"
     },
     {
        "x":5,
        "y":2,
        "color":"transparent"
     },
     {
        "x":6,
        "y":2,
        "color":"transparent"
     },
     {
        "x":7,
        "y":2,
        "color":"#31dd00"
     },
     {
        "x":8,
        "y":2,
        "color":"transparent"
     },
     {
        "x":9,
        "y":2,
        "color":"transparent"
     },
     {
        "x":10,
        "y":2,
        "color":"#ffEE00"
     },
     {
        "x":11,
        "y":2,
        "color":"transparent"
     },
     {
        "x":12,
        "y":2,
        "color":"transparent"
     },
     {
        "x":13,
        "y":2,
        "color":"#ffb500"
     },
     {
        "x":14,
        "y":2,
        "color":"transparent"
     },
     {
        "x":15,
        "y":2,
        "color":"transparent"
     },
     {
        "x":0,
        "y":4,
        "color":"transparent"
     },
     {
        "x":1,
        "y":4,
        "color":"transparent"
     },
     {
        "x":2,
        "y":4,
        "color":"#31dd00"
     },
     {
        "x":3,
        "y":4,
        "color":"transparent"
     },
     {
        "x":4,
        "y":4,
        "color":"transparent"
     },
     {
        "x":5,
        "y":4,
        "color":"#31dd00"
     },
     {
        "x":6,
        "y":4,
        "color":"transparent"
     },
     {
        "x":7,
        "y":4,
        "color":"transparent"
     },
     {
        "x":8,
        "y":4,
        "color":"#31dd00"
     },
     {
        "x":9,
        "y":4,
        "color":"transparent"
     },
     {
        "x":10,
        "y":4,
        "color":"transparent"
     },
     {
        "x":11,
        "y":4,
        "color":"#ffEE00"
     },
     {
        "x":12,
        "y":4,
        "color":"transparent"
     },
     {
        "x":13,
        "y":4,
        "color":"transparent"
     },
     {
        "x":14,
        "y":4,
        "color":"#ffb500"
     },
     {
        "x":15,
        "y":4,
        "color":"transparent"
     },
     {
        "x":0,
        "y":6,
        "color":"#31dd00"
     },
     {
        "x":1,
        "y":6,
        "color":"transparent"
     },
     {
        "x":2,
        "y":6,
        "color":"transparent"
     },
     {
        "x":3,
        "y":6,
        "color":"#31dd00"
     },
     {
        "x":4,
        "y":6,
        "color":"transparent"
     },
     {
        "x":5,
        "y":6,
        "color":"transparent"
     },
     {
        "x":6,
        "y":6,
        "color":"#31dd00"
     },
     {
        "x":7,
        "y":6,
        "color":"transparent"
     },
     {
        "x":8,
        "y":6,
        "color":"transparent"
     },
     {
        "x":9,
        "y":6,
        "color":"#31dd00"
     },
     {
        "x":10,
        "y":6,
        "color":"transparent"
     },
     {
        "x":11,
        "y":6,
        "color":"transparent"
     },
     {
        "x":12,
        "y":6,
        "color":"#ffEE00"
     },
     {
        "x":13,
        "y":6,
        "color":"transparent"
     },
     {
        "x":14,
        "y":6,
        "color":"transparent"
     },
     {
        "x":15,
        "y":6,
        "color":"#ffb500"
     },
     {
        "x":0,
        "y":8,
        "color":"transparent"
     },
     {
        "x":1,
        "y":8,
        "color":"#31dd00"
     },
     {
        "x":2,
        "y":8,
        "color":"transparent"
     },
     {
        "x":3,
        "y":8,
        "color":"transparent"
     },
     {
        "x":4,
        "y":8,
        "color":"#31dd00"
     },
     {
        "x":5,
        "y":8,
        "color":"transparent"
     },
     {
        "x":6,
        "y":8,
        "color":"transparent"
     },
     {
        "x":7,
        "y":8,
        "color":"#31dd00"
     },
     {
        "x":8,
        "y":8,
        "color":"transparent"
     },
     {
        "x":9,
        "y":8,
        "color":"transparent"
     },
     {
        "x":10,
        "y":8,
        "color":"#31dd00"
     },
     {
        "x":11,
        "y":8,
        "color":"transparent"
     },
     {
        "x":12,
        "y":8,
        "color":"transparent"
     },
     {
        "x":13,
        "y":8,
        "color":"#ffEE00"
     },
     {
        "x":14,
        "y":8,
        "color":"transparent"
     },
     {
        "x":15,
        "y":8,
        "color":"transparent"
     },
     {
        "x":0,
        "y":10,
        "color":"transparent"
     },
     {
        "x":1,
        "y":10,
        "color":"transparent"
     },
     {
        "x":2,
        "y":10,
        "color":"#31dd00"
     },
     {
        "x":3,
        "y":10,
        "color":"transparent"
     },
     {
        "x":4,
        "y":10,
        "color":"transparent"
     },
     {
        "x":5,
        "y":10,
        "color":"#31dd00"
     },
     {
        "x":6,
        "y":10,
        "color":"transparent"
     },
     {
        "x":7,
        "y":10,
        "color":"transparent"
     },
     {
        "x":8,
        "y":10,
        "color":"#31dd00"
     },
     {
        "x":9,
        "y":10,
        "color":"transparent"
     },
     {
        "x":10,
        "y":10,
        "color":"transparent"
     },
     {
        "x":11,
        "y":10,
        "color":"#31dd00"
     },
     {
        "x":12,
        "y":10,
        "color":"transparent"
     },
     {
        "x":13,
        "y":10,
        "color":"transparent"
     },
     {
        "x":14,
        "y":10,
        "color":"#ffEE00"
     },
     {
        "x":15,
        "y":10,
        "color":"transparent"
     },
     {
        "x":0,
        "y":12,
        "color":"#00ccff"
     },
     {
        "x":1,
        "y":12,
        "color":"transparent"
     },
     {
        "x":2,
        "y":12,
        "color":"transparent"
     },
     {
        "x":3,
        "y":12,
        "color":"#31dd00"
     },
     {
        "x":4,
        "y":12,
        "color":"transparent"
     },
     {
        "x":5,
        "y":12,
        "color":"transparent"
     },
     {
        "x":6,
        "y":12,
        "color":"#31dd00"
     },
     {
        "x":7,
        "y":12,
        "color":"transparent"
     },
     {
        "x":8,
        "y":12,
        "color":"transparent"
     },
     {
        "x":9,
        "y":12,
        "color":"#31dd00"
     },
     {
        "x":10,
        "y":12,
        "color":"transparent"
     },
     {
        "x":11,
        "y":12,
        "color":"transparent"
     },
     {
        "x":12,
        "y":12,
        "color":"#31dd00"
     },
     {
        "x":13,
        "y":12,
        "color":"transparent"
     },
     {
        "x":14,
        "y":12,
        "color":"transparent"
     },
     {
        "x":15,
        "y":12,
        "color":"transparent"
     },
     {
        "x":0,
        "y":14,
        "color":"transparent"
     },
     {
        "x":1,
        "y":14,
        "color":"transparent"
     },
     {
        "x":2,
        "y":14,
        "color":"transparent"
     },
     {
        "x":3,
        "y":14,
        "color":"transparent"
     },
     {
        "x":4,
        "y":14,
        "color":"transparent"
     },
     {
        "x":5,
        "y":14,
        "color":"transparent"
     },
     {
        "x":6,
        "y":14,
        "color":"transparent"
     },
     {
        "x":7,
        "y":14,
        "color":"transparent"
     },
     {
        "x":8,
        "y":14,
        "color":"transparent"
     },
     {
        "x":9,
        "y":14,
        "color":"transparent"
     },
     {
        "x":10,
        "y":14,
        "color":"transparent"
     },
     {
        "x":11,
        "y":14,
        "color":"transparent"
     },
     {
        "x":12,
        "y":14,
        "color":"transparent"
     },
     {
        "x":13,
        "y":14,
        "color":"transparent"
     },
     {
        "x":14,
        "y":14,
        "color":"transparent"
     },
     {
        "x":15,
        "y":14,
        "color":"transparent"
     }
  ],
  [
     {
        "x":0,
        "y":0,
        "color":"transparent"
     },
     {
        "x":1,
        "y":0,
        "color":"transparent"
     },
     {
        "x":2,
        "y":0,
        "color":"transparent"
     },
     {
        "x":3,
        "y":0,
        "color":"transparent"
     },
     {
        "x":4,
        "y":0,
        "color":"transparent"
     },
     {
        "x":5,
        "y":0,
        "color":"transparent"
     },
     {
        "x":6,
        "y":0,
        "color":"transparent"
     },
     {
        "x":7,
        "y":0,
        "color":"transparent"
     },
     {
        "x":8,
        "y":0,
        "color":"transparent"
     },
     {
        "x":9,
        "y":0,
        "color":"transparent"
     },
     {
        "x":10,
        "y":0,
        "color":"transparent"
     },
     {
        "x":11,
        "y":0,
        "color":"transparent"
     },
     {
        "x":12,
        "y":0,
        "color":"transparent"
     },
     {
        "x":13,
        "y":0,
        "color":"transparent"
     },
     {
        "x":14,
        "y":0,
        "color":"transparent"
     },
     {
        "x":15,
        "y":0,
        "color":"transparent"
     },
     {
        "x":0,
        "y":2,
        "color":"#31dd00"
     },
     {
        "x":1,
        "y":2,
        "color":"transparent"
     },
     {
        "x":2,
        "y":2,
        "color":"transparent"
     },
     {
        "x":3,
        "y":2,
        "color":"#31dd00"
     },
     {
        "x":4,
        "y":2,
        "color":"transparent"
     },
     {
        "x":5,
        "y":2,
        "color":"transparent"
     },
     {
        "x":6,
        "y":2,
        "color":"#31dd00"
     },
     {
        "x":7,
        "y":2,
        "color":"transparent"
     },
     {
        "x":8,
        "y":2,
        "color":"transparent"
     },
     {
        "x":9,
        "y":2,
        "color":"#31dd00"
     },
     {
        "x":10,
        "y":2,
        "color":"transparent"
     },
     {
        "x":11,
        "y":2,
        "color":"transparent"
     },
     {
        "x":12,
        "y":2,
        "color":"#ffb500"
     },
     {
        "x":13,
        "y":2,
        "color":"transparent"
     },
     {
        "x":14,
        "y":2,
        "color":"transparent"
     },
     {
        "x":15,
        "y":2,
        "color":"#ffEE00"
     },
     {
        "x":0,
        "y":4,
        "color":"transparent"
     },
     {
        "x":1,
        "y":4,
        "color":"#31dd00"
     },
     {
        "x":2,
        "y":4,
        "color":"transparent"
     },
     {
        "x":3,
        "y":4,
        "color":"transparent"
     },
     {
        "x":4,
        "y":4,
        "color":"#31dd00"
     },
     {
        "x":5,
        "y":4,
        "color":"transparent"
     },
     {
        "x":6,
        "y":4,
        "color":"transparent"
     },
     {
        "x":7,
        "y":4,
        "color":"#31dd00"
     },
     {
        "x":8,
        "y":4,
        "color":"transparent"
     },
     {
        "x":9,
        "y":4,
        "color":"transparent"
     },
     {
        "x":10,
        "y":4,
        "color":"#31dd00"
     },
     {
        "x":11,
        "y":4,
        "color":"transparent"
     },
     {
        "x":12,
        "y":4,
        "color":"transparent"
     },
     {
        "x":13,
        "y":4,
        "color":"#ffb500"
     },
     {
        "x":14,
        "y":4,
        "color":"transparent"
     },
     {
        "x":15,
        "y":4,
        "color":"transparent"
     },
     {
        "x":0,
        "y":6,
        "color":"transparent"
     },
     {
        "x":1,
        "y":6,
        "color":"transparent"
     },
     {
        "x":2,
        "y":6,
        "color":"#31dd00"
     },
     {
        "x":3,
        "y":6,
        "color":"transparent"
     },
     {
        "x":4,
        "y":6,
        "color":"transparent"
     },
     {
        "x":5,
        "y":6,
        "color":"#31dd00"
     },
     {
        "x":6,
        "y":6,
        "color":"transparent"
     },
     {
        "x":7,
        "y":6,
        "color":"transparent"
     },
     {
        "x":8,
        "y":6,
        "color":"#31dd00"
     },
     {
        "x":9,
        "y":6,
        "color":"transparent"
     },
     {
        "x":10,
        "y":6,
        "color":"transparent"
     },
     {
        "x":11,
        "y":6,
        "color":"#31dd00"
     },
     {
        "x":12,
        "y":6,
        "color":"transparent"
     },
     {
        "x":13,
        "y":6,
        "color":"transparent"
     },
     {
        "x":14,
        "y":6,
        "color":"#ffb500"
     },
     {
        "x":15,
        "y":6,
        "color":"transparent"
     },
     {
        "x":0,
        "y":8,
        "color":"#00ccff"
     },
     {
        "x":1,
        "y":8,
        "color":"transparent"
     },
     {
        "x":2,
        "y":8,
        "color":"transparent"
     },
     {
        "x":3,
        "y":8,
        "color":"#31dd00"
     },
     {
        "x":4,
        "y":8,
        "color":"transparent"
     },
     {
        "x":5,
        "y":8,
        "color":"transparent"
     },
     {
        "x":6,
        "y":8,
        "color":"#31dd00"
     },
     {
        "x":7,
        "y":8,
        "color":"transparent"
     },
     {
        "x":8,
        "y":8,
        "color":"transparent"
     },
     {
        "x":9,
        "y":8,
        "color":"#31dd00"
     },
     {
        "x":10,
        "y":8,
        "color":"transparent"
     },
     {
        "x":11,
        "y":8,
        "color":"transparent"
     },
     {
        "x":12,
        "y":8,
        "color":"#31dd00"
     },
     {
        "x":13,
        "y":8,
        "color":"transparent"
     },
     {
        "x":14,
        "y":8,
        "color":"transparent"
     },
     {
        "x":15,
        "y":8,
        "color":"#ffb500"
     },
     {
        "x":0,
        "y":10,
        "color":"transparent"
     },
     {
        "x":1,
        "y":10,
        "color":"#00ccff"
     },
     {
        "x":2,
        "y":10,
        "color":"transparent"
     },
     {
        "x":3,
        "y":10,
        "color":"transparent"
     },
     {
        "x":4,
        "y":10,
        "color":"#31dd00"
     },
     {
        "x":5,
        "y":10,
        "color":"transparent"
     },
     {
        "x":6,
        "y":10,
        "color":"transparent"
     },
     {
        "x":7,
        "y":10,
        "color":"#31dd00"
     },
     {
        "x":8,
        "y":10,
        "color":"transparent"
     },
     {
        "x":9,
        "y":10,
        "color":"transparent"
     },
     {
        "x":10,
        "y":10,
        "color":"#31dd00"
     },
     {
        "x":11,
        "y":10,
        "color":"transparent"
     },
     {
        "x":12,
        "y":10,
        "color":"transparent"
     },
     {
        "x":13,
        "y":10,
        "color":"#31dd00"
     },
     {
        "x":14,
        "y":10,
        "color":"transparent"
     },
     {
        "x":15,
        "y":10,
        "color":"transparent"
     },
     {
        "x":0,
        "y":12,
        "color":"transparent"
     },
     {
        "x":1,
        "y":12,
        "color":"transparent"
     },
     {
        "x":2,
        "y":12,
        "color":"#00ccff"
     },
     {
        "x":3,
        "y":12,
        "color":"transparent"
     },
     {
        "x":4,
        "y":12,
        "color":"transparent"
     },
     {
        "x":5,
        "y":12,
        "color":"#31dd00"
     },
     {
        "x":6,
        "y":12,
        "color":"transparent"
     },
     {
        "x":7,
        "y":12,
        "color":"transparent"
     },
     {
        "x":8,
        "y":12,
        "color":"#31dd00"
     },
     {
        "x":9,
        "y":12,
        "color":"transparent"
     },
     {
        "x":10,
        "y":12,
        "color":"transparent"
     },
     {
        "x":11,
        "y":12,
        "color":"#31dd00"
     },
     {
        "x":12,
        "y":12,
        "color":"transparent"
     },
     {
        "x":13,
        "y":12,
        "color":"transparent"
     },
     {
        "x":14,
        "y":12,
        "color":"#31dd00"
     },
     {
        "x":15,
        "y":12,
        "color":"transparent"
     },
     {
        "x":0,
        "y":14,
        "color":"transparent"
     },
     {
        "x":1,
        "y":14,
        "color":"transparent"
     },
     {
        "x":2,
        "y":14,
        "color":"transparent"
     },
     {
        "x":3,
        "y":14,
        "color":"transparent"
     },
     {
        "x":4,
        "y":14,
        "color":"transparent"
     },
     {
        "x":5,
        "y":14,
        "color":"transparent"
     },
     {
        "x":6,
        "y":14,
        "color":"transparent"
     },
     {
        "x":7,
        "y":14,
        "color":"transparent"
     },
     {
        "x":8,
        "y":14,
        "color":"transparent"
     },
     {
        "x":9,
        "y":14,
        "color":"transparent"
     },
     {
        "x":10,
        "y":14,
        "color":"transparent"
     },
     {
        "x":11,
        "y":14,
        "color":"transparent"
     },
     {
        "x":12,
        "y":14,
        "color":"transparent"
     },
     {
        "x":13,
        "y":14,
        "color":"transparent"
     },
     {
        "x":14,
        "y":14,
        "color":"transparent"
     },
     {
        "x":15,
        "y":14,
        "color":"transparent"
     }
  ]
]

export default frames;